### PR TITLE
Fix bug in training error calculation

### PR DESCRIPTION
**Pull request by Sunt-ing**
Previously, the training error is calculated by the `abs( avg(predicted_time/rea_time)-1.0 )`, which is wrong because predicted_time can be larger or smaller than real_time. And according to the given sample, the value is 0.053681%, which is too low to be the truth.
Therefore, I adjust the formula and now it is `avg( abs(predicted_time/rea_time-1.0) )`. And according to the given sample, the value is 1.335098% now, which is more consistent with the results of your experiments actually.

### CODE REVIEW

**Comment by Sunt-ing** [comment]
Sorry to bother you. Am I wrong? @shivaram

**Comment by shivaram** [comment]
Thanks @Sunt-ing -- I'm not sure where in the old code was `abs` being used. That said I understand the source of your confusion. Given that this calculation is to just print an informational message maybe we can just print the mean of the ratios of predicted vs. actual? That is we can avoid doing the `-1.0`

**Comment by Sunt-ing** [comment]
Thanks for your reply @shivaram  -- I realize that `abs` is not used before. 
Yet, I think `abs` can make the informational message more accurate. Without the `abs`, the printed message may not make much sense. 
By the way, can Ernest be applied to Apache Flink directly?

**Comment by shivaram** [comment]
Right. Thats why my proposal was to get rid of the percentage altogether and only report ratios -- would you be able to update this PR make that change? 

I have not tried to use this with Flink and am not sure if it can be directly applied

**Comment by Sunt-ing** [comment]
Great! I have updated the PR. How about this? @shivaram

**Comment by shivaram** [comment]
LGTM. Thanks @Sunt-ing

**Comment by Sunt-ing** [comment]
> LGTM. Thanks @Sunt-ing

Thanks!

**Pull request merged**
